evensive/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'evensive.views.home', name='home'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^projects/', include('projects.urls')),
    url(r'^members/', include('members.urls')),
    url(r'^companies/', include('companies.urls')),

]

members/urls.py
from django.conf.urls import patterns, url

from members import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='members'),
    url(r'^(?P<member_id>\d+)$', views.detail, name='member_detail'),
)

projects/urls.py
from django.conf.urls import url

from projects import views

urlpatterns = [
    url(r'^$', views.index, name='projects'),
    url(r'^(?P<project_id>[0-9]+)/overview$', views.overview, name='project_overview'),
    url(r'^(?P<project_id>[0-9]+)/tasks$', views.tasks, name='project_tasks'),
    url(r'^(?P<project_id>[0-9]+)/tasks/(?P<task_id>[0-9]+)$', views.task, name='project_task'),
    url(r'^(?P<project_id>[0-9]+)/milestones$', views.milestones, name='project_milestones'),
    url(r'^(?P<project_id>[0-9]+)/milestones/(?P<milestone_id>[0-9]+)$', views.milestone, name='project_milestone')

]

projects/models.py
from django.db import models

from companies.models import Company
from members.models import Member

class Project(models.Model):
    name = models.CharField(max_length=50)
    company = models.ForeignKey(Company)

    def __str__(self):
        return self.name

    def get_total_duration(self):
        duration = 0
        for task in self.task_set.all():
            duration += task.duration

        return duration

class Milestone(models.Model):
    name = models.CharField(max_length=125)
    due_date = models.DateField()
    project = models.ForeignKey(Project)
    created_by = models.ForeignKey(Member, related_name="miletone_created_by")

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=125)
    project = models.ForeignKey(Project)
    description = models.TextField()
    milestone = models.ForeignKey(Milestone, blank=True, null=True)
    duration = models.IntegerField()
    assigned_to = models.ForeignKey(Member, related_name="assign_to", blank=True, null=True)
    created_by = models.ForeignKey(Member, related_name="task_created_by")
    creation_date = models.DateTimeField(auto_now_add=True)
    actions = models.ManyToManyField(Member, through="Action")

    def __str__(self):
        return self.name


class Action(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    task = models.ForeignKey(Task)
    member = models.ForeignKey(Member)
    elapsed_time = models.IntegerField()
    progression  = models.IntegerField()

projects/forms.py
from django.forms import ModelForm
from projects.models import Milestone, Project, Task

class MilestoneForm(ModelForm):
    class Meta:
        model = Milestone
        fields = ['name', 'due_date']

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = '__all__'
        exclude = ['project', 'created_by', 'description']


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = '__all__'

projects/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect

from companies.forms import CompanyForm
from members.models import Member
from projects.forms import MilestoneForm, ProjectForm, TaskForm
from projects.models import Milestone, Project, Task


def index(request):
    projects = Project.objects.all()
    companyForm = CompanyForm()
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save()
            return JsonResponse({
                'status': 'success',
                'message': 'New task created'
            })
        else:
            return JsonResponse({
                'status': 'error',
                'message': form.errors
            })
    else:
        form = ProjectForm()
    return render(
        request,
        'projects/index.html',
        {'projects': projects, 'addProjectForm': form, 'addCompanyForm': CompanyForm})

def overview(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    return render(
        request,
        'projects/overview.html',
        {'project': project})


def tasks(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    tasks = Task.objects.filter(project=project)

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.project = project
            task.created_by = Member.objects.get(pk=1)
            task.save()
            return JsonResponse({
                'status': 'success',
                'message': 'New task created'
            })
        else:
            return JsonResponse({
                'status': 'error',
                'message': form.errors
            })
    else:
        form = TaskForm()

    return render(
        request,
        'projects/tasks.html',{
            'project': project,
            'addTaskForm': form,
            'tasks': tasks
        })

def task(request, project_id, task_id):
    project = get_object_or_404(Project, pk=project_id)
    task = get_object_or_404(Task, pk=task_id)

    return render(
        request,
        'projects/task.html',{
            'project': project,
            'task': task
        })

def milestones(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    milestones = Milestone.objects.filter(project=project)

    if request.method == 'POST':
        form = MilestoneForm(request.POST)
        if form.is_valid():
            milestone = form.save(commit=False)
            milestone.project = project
            milestone.created_by = Member.objects.get(pk=1)
            milestone.save()
            return JsonResponse({
                'status': 'success',
                'message': 'New milestone created'
            })
        else:
            return JsonResponse({
                'status': 'error',
                'message': form.errors
            })
    else:
        form = MilestoneForm()

    return render(
        request,
        'projects/milestones.html',{
            'project': project,
            'addMilestoneForm': form,
            'milestones': milestones
        })

def milestone(request, project_id, milestone_id):
    project = get_object_or_404(Project, pk=project_id)
    milestone = get_object_or_404(Milestone, pk=milestone_id)

    return render(
        request,
        'projects/milestone.html',{
            'project': project,
            'milestone': milestone
        })

projects/templates/projects/base_projects.html
{% extends "base.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li role="menuitem"><a href="{% url "projects" %}">Projects</a></li>
{% endblock %}

{% block content %}
    <div class="large-3 columns">
        {% block column %}{% endblock %}
    </div>
    <div class="large-9 columns">
        <ul class="tabs">
            <li class="tab-title" role="presentational" >
                <a href="{% url "project_overview" project.pk %}" role="tab" tabindex="0" aria-selected="true" controls="panel2-1">Overview</a>
            </li>
            <li class="tab-title" role="presentational" >
                <a href="{% url "project_milestones" project.pk %}" role="tab" tabindex="0" aria-selected="true" controls="panel2-1">Milestones</a>
            </li>
            <li class="tab-title" role="presentational" >
                <a href="{% url "project_tasks" project.pk %}" role="tab" tabindex="0" aria-selected="true" controls="panel2-1">Tasks</a>
            </li>
        </ul>
        {% block project_content %}{% endblock %}
    </div>
{% endblock %}

projects/templates/projects/index.html
{% extends "base.html"  %}
    {% block breadcrumb %}
        {{ block.super }}
        <li role="menuitem"><a href="{% url "projects" %}">Projects</a></li>
    {% endblock %}
{% block content %}
    {% if projects %}
        <ul>
            {% for project in projects %}
                <li><a href="{% url "project_overview" project.pk %}">{{ project.name }}</a></li>
            {% endfor %}
        </ul>
        <a href="" data-reveal-id="addProjectModal" class="button">Create a new project</a>

    {% else %}
        <a href="" data-reveal-id="addProjectModal" class="button">Create a new project</a>
    {% endif %}

    <div id="addProjectModal" class="reveal-modal" data-reveal aria-labelledby="Add a Project" aria-hidden="true" role="dialog">
      <h2 id="modalTitle">Add a new project</h2>
        <form id="addTaskForm" action="#" method="POST" data-url="{% url "projects" %}">{% csrf_token %}
            {{ addProjectForm }}
            <p><a href="#" data-reveal-id="addCompanyModal" class="secondary button">+</a></p>
            <button type="submit">Submit</button>
        </form>
      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>

    <div id="addCompanyModal" class="reveal-modal" data-reveal aria-labelledby="Add a Company" aria-hidden="true" role="dialog">
      <h2 id="modalTitle">Add a new company</h2>
        <form id="addCompanyForm" action="#" method="POST" data-url="{% url "companies" %}">{% csrf_token %}
            {{ addCompanyForm }}
            <button type="submit">Submit</button>
        </form>
      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>

{% endblock %}

projects/templates/projects/milestone.html
{% extends "projects/base_projects.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li role="menuitem"><a href="{% url "project_overview" project.pk %}">{{ project.name }}</a></li>
    <li role="menuitem"><a href="{% url "project_milestones" project.pk %}">Miletones</a></li>
    <li role="menuitem"><a href="{% url "project_milestone" project_id=project.pk milestone_id=milestone.pk%}">{{ milestone.name }}</a></li>
{% endblock %}

{% block column %}
    {{ project.name }}
{% endblock %}

{% block project_content %}
    <h2>{{ milestone.name }}</h2>
    <ul>
        {% for task in milestone.task_set.all %}
            <li><a href="{% url "project_task" project_id=project.pk task_id=task.pk %}">{{  task.name }}</a></li>
            Duration: {{ task.duration }}
        {% endfor %}
    </ul>
    {% endblock %}

projects/templates/projects/milestones.html
{% extends "projects/base_projects.html" %}
{% block page-title %}
    {{ project.name }} - Milestones
{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li role="menuitem"><a href="{% url "project_overview" project.pk %}">{{ project.name }}</a></li>
{% endblock %}

{% block column %}
    {{ project.name }}
    Milestone
{% endblock %}

{% block project_content %}
    <h2>Milestones</h2>
    {% if milestones %}
        <ul>
            {% for milestone in milestones%}
                <li><a href="{% url "project_milestone" project_id=project.pk milestone_id=milestone.pk %}">{{ milestone.name }}</a></li>
            {% endfor %}
        </ul>
        <a href="#" data-reveal-id="addMilestoneModal" class="button success">Add a new one</a>
    {% else %}
        <p>No Milestone</p>
        <a href="#" data-reveal-id="addMilestoneModal" class="button success">Add One</a>
    {% endif %}


    <div id="addMilestoneModal" class="reveal-modal" data-reveal aria-labelledby="Add a milestone" aria-hidden="true" role="dialog">
      <h2 id="modalTitle">Add a milestone.</h2>

        <form id="addMilestoneForm" action="#" method="POST" data-url="{% url "project_milestones" project.pk %}">{% csrf_token %}
            {{ addMilestoneForm }}
            <button type="submit">Submit</button>
        </form>
      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>
{% endblock %}

projects/templates/projects/overview.html
{% extends "projects/base_projects.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li role="menuitem"><a href="{% url "project_overview" project.pk %}">{{ project.name }}</a></li>
{% endblock %}

{% block column %}
    {{ project.name }}
    Overview
{% endblock %}

{% block project_content %}
    <h2>Overview</h2>
    Number of Tasks: {{ project.task_set.all.count }}
    Total duration: {{ project.get_total_duration }}
{% endblock %}

projects/templates/projects/task.html
{% extends "projects/base_projects.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li role="menuitem"><a href="{% url "project_overview" task.project.pk %}">{{ task.project.name }}</a></li>
    <li role="menuitem"><a href="{% url "project_tasks" task.project.pk %}">Tasks</a></li>
    <li role="menuitem"><a href="{% url "project_task" project_id=task.project.pk task_id=task.pk%}">{{ task.name }}</a></li>
{% endblock %}

{% block column %}
    {{ task.project.name }}
    Tasks
{% endblock %}

{% block project_content %}
    <h2>{{ task.name }}</h2>
<p>Created by {{ task.created_by }} on {{ task.creation_date }}</p>
    <p>{{ task.description }}</p>
    <p>Assigned to : {{ task }}</p>
    <p>Estimated duration: {{ task.duration }} Hours</p>

    <p>History</p>
    <table>
        <thead>
            <tr>
                <th width="200">Date</th>
                <th>Elapsed time</th>
                <th>Progession</th>
            </tr>
        </thead>
        <tbody>
        {% for action in task.action_set.all %}
            <tr>
                <td>{{ action.date }}</td>
                <td>{{ action.elapsed_time }}</td>
                <td>{{ action.progression }}</td>
            </tr>
        {% endfor %}
        </tbody>

    </table>

{% endblock %}

projects/templates/projects/tasks.html
{% extends "projects/base_projects.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li role="menuitem"><a href="{% url "project_overview" project.pk %}">{{ project.name }}</a></li>
{% endblock %}

{% block column %}
    {{ project.name }}
    Tasks
{% endblock %}

{% block project_content %}
    <h2>Tasks</h2>
    {% if tasks %}
        <ul>
            {% for task in tasks %}
                <li>
                    <a href="{% url "project_task" project_id=task.project.pk task_id=task.id %}">{{ task.name }}</a>
                    Duration: {{ task.duration }}
                </li>
            {% endfor %}
        </ul>
        <a href="#" data-reveal-id="addTaskModal" class="button success">Add One</a>

    {% else %}
        <p>No Task</p>
        <a href="#" data-reveal-id="addTaskModal" class="button success">Add One</a>
    {% endif %}

    <div id="addTaskModal" class="reveal-modal" data-reveal aria-labelledby="Add a Task" aria-hidden="true" role="dialog">
      <h2 id="modalTitle">Add a task.</h2>

        <form id="addTaskForm" action="#" method="POST" data-url="{% url "project_tasks" project.pk %}">{% csrf_token %}
            {{ addTaskForm }}
            <button type="submit">Submit</button>
        </form>
      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>

{% endblock %}